config/routes.rb
Rails.application.routes.draw do
devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :users do
    resources :tweets
  end

  resources :followings
  root to: 'users#index'
end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :user
  belongs_to :followed, :class_name => "User"

  after_create :email_confirmation

  def email_confirmation
    @user = User.find(self.user_id)
    @followed = User.find(self.followed_id)
    UserMailer.following_confirmation(@followed, @user).deliver
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :email

  has_many :followings
  has_many :followeds, :through => :followings
  has_many :inverse_followings, :class_name => "Following", :foreign_key => "followed_id"
  has_many :inverse_followeds, :through => :inverse_followings, :source => :user, :foreign_key => "user_email"

  has_many :tweets
  after_create :send_signup_email

  def send_signup_email
    UserMailer.signup_confirmation(self).deliver
  end

  def tweets_of_followers
    tweets = []
    self.followings.map { |following| following.followed }.each do |user|
      user.tweets.each { |tweet| tweets << tweet }
    end
    tweets

    # @all_tweets = @user_tweets.map { |user| user.tweets}.flatten
    # @each_tweet = @all_tweets.map { |tweet| tweet.content}.flatten
    # @every_tweet = @each_tweet
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(current_user)
    user_path(current_user)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    @followed = User.find(params[:followed_id])
    @following = current_user.followings.build(:followed_id => params[:followed_id], :user_email => current_user.email)
    if @following.save
      flash[:notice] = "Added follow."
      redirect_to root_url
    else
      flash[:error] = "Unable to follow."
      redirect_to root_url
    end
  end

def destroy
  @following = current_user.followings.find(params[:id])
  @following.destroy
  flash[:notice] = "Removed following."
  redirect_to current_user
end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @tweets = @user.tweets.all
  end

  def new
    @user = User.find(params[:user_id])
    @tweet = @user.tweets.new
  end

  def create
    @user = User.find(params[:user_id])
    @tweet = @user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to user_tweets_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:user_id])
    @tweet = @user.tweets.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:edit, :update, :show, :destroy]

  def index
    @users = User.all.order("email").page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets_of_followers

    # @tweets = @user.followings.page(params[:page]).per(1)
  end

  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     binding.pry
  #     UserMailer.signup_confirmation(@user).deliver
  #     session[:user_id] = @user.id
  #     flash[:notice] = "User was added"
  #     redirect_to session_user_path(session, @user)
  #   else
  #     render 'new'
  #   end
  # end the devise controller is in effect

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @current_user.id == @user.id
      if @user.update(user_params)
        @user.update_attribute(:email, params[:user])
        flash[:notice] = "User updated."
        redirect_to session_user_path(session, @user)
      else
        render 'edit'
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @current_user.id == @user.id
      if @user.destroy
        current_user.destroy
        session[:user_id] = nil
        flash[:notice] = "The user was deleted."
        redirect_to root_path
      end
    end
  end



  private


  def authorize
    @user = User.find(params[:id])
    redirect_to login_url, alert: "Not authorized!" if current_user != @user
  end


    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <nav class="navbar navbar-inverse fixed navbar-custom" role="navigation">
    <div class="container">
      <ul class="nav navbar-nav title">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <p><%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %> |
          <%= link_to "Tweet", new_user_tweet_path(current_user) %></p>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </ul>
    </div>
  </nav>
<body>
  <div class="container">
    <div class="alert">
      <%= flash[:notice] %>
    </div>
    <%= yield %><br/>
    <%= debug(params) %>
  </div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for @tweet, :url => user_tweets_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/tweets/index.html.erb
<table>
  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <tr><td><%= tweet.content %></td></tr>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render'form' %>

app/views/tweets/show.html.erb
<h1><%= @user.email %></h1>

<h3><%= @tweet.content %></h3>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <br/>

  <div class="actions">
    <%= f.submit :class => "btn btn-success btn-xs" %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form' %>

<%= link_to 'Show', session_user_path(session, current_user) %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <tr><td><%=h user.email %></td><td><%= link_to "Follow", followings_path(:followed_id => user), :method => :post %></td></tr>
      </tr>
    <% end %>
    <%= paginate @users %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<table><tr><td>
<p>
  <strong>User:</strong>
  <%= current_user.email %><br/>
</p>

<ul>
  <% for following in @user.followings %>
    <li>Following:
      <%=h following.followed.email %>
      (<%= link_to "remove", following, :method => :delete %>)
    </li>
  <% end %>
</ul></td><br>
<td>
<ul>


  <br>
  <% for tweet in @tweets%>
     <br> <strong><%= tweet.content %></strong> TWEETED BY: <%= tweet.user.email %>
  <% end %>
</ul></td></tr></table>

<p><%= link_to "Find users to follow", users_path %></p>


<h3>Following You:</h3>
  <ul>
    <% for user in @user.inverse_followings %>
      <li><%=h user.user_email %></li>
    <% end %>
  </ul>